export interface Station {
  id: number
  tipo: "Estación de carga" | "Punto de carga"
  name: string
  address: string
  link: string
  horario: string
  observaciones?: string
  status: "available" | "busy" | "maintenance"
  lat: number
  lng: number
  ciudad: string
  estado: string
}

export const stations: Station[] = [
  {
    id: 1,
    tipo: "Estación de carga",
    name: "La Viga",
    address: "Calz. de la Viga 667, Barrio de Zapotla, Iztacalco, 08230, CDMX",
    link: "https://maps.app.goo.gl/QDKsxtqMcqetx2eB6",
    horario: "24 horas",
    status: "available",
    lat: 19.3959839,
    lng: -99.1235724,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 2,
    tipo: "Estación de carga",
    name: "Coyoacán",
    address: "Anillo de Circunvalación 37, Atlántida, Coyoacán, 04370, CDMX",
    link: "https://maps.app.goo.gl/qSV4TCsxPx1Nm4Ro6",
    horario: "24 horas",
    status: "available",
    lat: 19.3400027,
    lng: -99.1447717,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 3,
    tipo: "Estación de carga",
    name: "Querétaro",
    address: "Blvd. de las Américas 13, Lomas de Queretaro, 76190, Qro.",
    link: "https://maps.app.goo.gl/c9JAKR1SFfmfDhxH9",
    horario: "24 horas",
    status: "available",
    lat: 20.5732479,
    lng: -100.4050782,
    ciudad: "Querétaro",
    estado: "Querétaro",
  },
  {
    id: 4,
    tipo: "Punto de carga",
    name: "Plaza el Ángel",
    address: "Av Lago de Guadalupe 1003, Bosques de Ixtacala, 52919, Edo Méx.",
    link: "https://maps.app.goo.gl/YMA2AEdhkQF6bYjd8",
    horario: "8:00 am a 11:00 pm",
    status: "available",
    lat: 19.6101343,
    lng: -99.2410667,
    ciudad: "Atizapán de Zaragoza",
    estado: "Estado de México",
  },
  {
    id: 5,
    tipo: "Estación de carga",
    name: "Barrientos",
    address: "Autop. México Manzana 042, Industrial Barrientos, 54010, Tlalnepantla, Méx.",
    link: "https://maps.app.goo.gl/avdNQMuuJBnAQ9gU8",
    horario: "24 horas",
    status: "available",
    lat: 19.5268,
    lng: -99.2044,
    ciudad: "Tlalnepantla",
    estado: "Estado de México",
  },
  {
    id: 6,
    tipo: "Punto de carga",
    name: "BYD Iztacalco",
    address: "Av. Pdte. Plutarco Elías Calles 592, Barrio de Zapotla, Iztacalco, 08610, CDMX",
    link: "https://maps.app.goo.gl/SsUHE2aUqaXdSJ1K8",
    horario: "24 horas",
    status: "available",
    lat: 19.3977334,
    lng: -99.1219458,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 7,
    tipo: "Punto de carga",
    name: "BYD San Jerónimo",
    address: "Av. San Jerónimo 630, La Otra Banda, Álvaro Obregón, 01090, CDMX",
    link: "https://maps.app.goo.gl/zE5i1Q7ovE2UfCdv7",
    horario: "24 horas",
    status: "available",
    lat: 19.3277292,
    lng: -99.2117327,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 8,
    tipo: "Punto de carga",
    name: "BYD Tepic",
    address: "De Los Insurgentes Pte. 920, El Rodeo, 63060 Tepic, Nay.",
    link: "https://maps.app.goo.gl/zNog1DA8GDfQDUTP9",
    horario: "24 horas",
    status: "available",
    lat: 21.5197464,
    lng: -104.9177991,
    ciudad: "Tepic",
    estado: "Nayarit",
  },
  {
    id: 9,
    tipo: "Punto de carga",
    name: "Los Pinos Rentals",
    address: "Anillo Perif. 428, San Pedro de los Pinos, Álvaro Obregón, 01180, CDMX",
    link: "https://maps.app.goo.gl/5nQUafy37VYi4FnS7",
    horario: "8:00 am a 11:00 pm",
    status: "available",
    lat: 19.3918512,
    lng: -99.1892108,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 10,
    tipo: "Punto de carga",
    name: "Espacio Sur",
    address: "Gutiérrez Zamora 33, Águilas, Álvaro Obregón, 01710, CDMX",
    link: "https://maps.app.goo.gl/gJ7dDwKaGnffS1RC9",
    horario: "24 horas",
    status: "available",
    lat: 19.3581944,
    lng: -99.1998136,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 11,
    tipo: "Punto de carga",
    name: "Plaza Toba",
    address: "Av. de Las Fuentes 549, Jardines del Pedregal, Álvaro Obregón, 01900, CDMX",
    link: "https://maps.app.goo.gl/5LS9bUMqmSmdCrLM6",
    horario: "8:00 am a 11:00 pm",
    status: "available",
    lat: 19.3173467,
    lng: -99.2123549,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 12,
    tipo: "Punto de carga",
    name: "Guadalajara",
    address: "Av. de las Américas 594, Ladrón de Guevara, Ladron De Guevara, 44600, Guadalajara, Jal.",
    link: "https://maps.app.goo.gl/J9K4m3Xsr6qWXkzw5",
    horario: "8:00 pm a 7:00 am",
    status: "available",
    lat: 20.6870923,
    lng: -103.3731628,
    ciudad: "Guadalajara",
    estado: "Jalisco",
  },
  {
    id: 13,
    tipo: "Punto de carga",
    name: "Cuauhtémoc",
    address: "Av. Cuauhtémoc 694, Narvarte Poniente, Benito Juárez, 03020, CDMX",
    link: "https://maps.app.goo.gl/mjxrqj1EJRZ9Sz3r5",
    horario: "-",
    observaciones: "Pendiente de confirmación de horario",
    status: "available",
    lat: 19.3936618,
    lng: -99.1560542,
    ciudad: "Ciudad de México",
    estado: "CDMX",
  },
  {
    id: 14,
    tipo: "Estación de carga",
    name: "Puebla",
    address: "Cto Juan Pablo II 1729, La Noria, 72410 Heroica Puebla de Zaragoza, Pue.",
    link: "https://maps.app.goo.gl/Cz4CVGe2hYVeTiKRA",
    horario: "24 horas",
    status: "available",
    lat: 19.031848,
    lng: -98.2239451,
    ciudad: "Puebla",
    estado: "Puebla",
  },
  {
    id: 15,
    tipo: "Estación de carga",
    name: "Guadalajara",
    address: "Av. Dr. Roberto Michel 2305, El Rosario, 44895 Guadalajara, Jal.",
    link: "https://maps.app.goo.gl/ATKr1VsTg7iog8Yr6",
    horario: "24 horas",
    observaciones: "Próximamente",
    status: "maintenance",
    lat: 20.6351447,
    lng: -103.3300792,
    ciudad: "Guadalajara",
    estado: "Jalisco",
  },
  {
    id: 16,
    tipo: "Estación de carga",
    name: "Monterrey",
    address: "Av. Francisco I. Madero 742, Centro, 64720 Monterrey, N.L.",
    link: "https://maps.app.goo.gl/DpY7WPvAysQ8riR36",
    horario: "24 horas",
    observaciones: "Próximamente",
    status: "maintenance",
    lat: 25.6847062,
    lng: -100.3065716,
    ciudad: "Monterrey",
    estado: "Nuevo León",
  },
]
